config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'users#index'

  get '/signup', to: 'users#new', as: 'signup'
  get '/login', to: 'sessions#new', as: 'login'
  get '/logout', to: 'sessions#destroy', as: 'logout'

  resources :users, only: [:index, :new, :create, :show]
  resources :sessions, only: [:new, :create, :destroy]
  resources :events, only: [:index, :new, :create, :show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
    belongs_to :creator, class_name: "User"
    has_many :invitations, foreign_key: :attended_event_id
    has_many :attendees, through: :invitations

    scope :future, -> { where('date > ?', Date.today).order(:date) }
end

app/models/invitation.rb
class Invitation < ApplicationRecord
    belongs_to :attendee, class_name: "User"
    belongs_to :attended_event, class_name: "Event"
end

app/models/user.rb
class User < ApplicationRecord
    has_many :created_events, foreign_key: :creator_id, class_name: "Event"
    has_many :invitations, foreign_key: :attendee_id
    has_many :attended_events, through: :invitations
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    private

    def current_user
        @current_user ||= User.find(session[:current_user_id]) if session[:current_user_id]
    end

    helper_method :current_user
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
    def index
        @events = Event.all
    end

    def new
        @event = Event.new
    end

    def create
        @event = current_user.created_events.build(event_params)

        if @event.save
            flash[:notice] = "Event creation successful!"
            redirect_to root_path
        else
            render :new
        end
    end

    def show
        @event = Event.find(params[:id])
    end

    def event_params
        params.require(:event).permit(:title, :description, :date)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new
    end

    def create
        user = User.find_by username: params[:username]

        if user
            session[:current_user_id] = user.id
            flash[:notice] = "Login Successful!"
            redirect_to root_path
        else
            flash.now.alert = "No user with that name exists!"
            render :new
        end
    end

    def destroy
        session[:current_user_id] = nil
        redirect_to root_path
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def index
        @users = User.all
    end

    def new
        @user = User.new
    end

    def create
        @user = User.new(user_params)

        if @user.save
            session[:current_user_id] = @user.id
            flash[:notice] = "Account creation successful!"
            redirect_to root_path
        else
            render :new
        end
    end

    def show
        @user = User.find((params[:id]))
    end

    private
    
    def user_params
        params.require(:user).permit(:username)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/index.html.erb
<h1>All events</h1>

<% @events.each do |event|%>
    <div>
        <%= link_to event.title, event_path(event) %>
    </div>
<% end %>

<h4>Future Events</h4>
<% @events.future.each do |future_event| %>
    <p><%= future_event.title %></p>
<% end %>

app/views/events/new.html.erb
<h1>Create a new event</h1>

<%= form_with model: @event do |form| %>
    <div>
        <%= form.label :title %>
        <%= form.text_field :title %>
    </div>
    <div>
        <%= form.label :description %>
        <%= form.text_field :description %>
    </div>
    <div>
        <%= form.label :date %>
        <%= form.date_field :date %>
    </div>
    <%= form.submit "Create Event" %>
<% end %>

app/views/events/show.html.erb
<h1><%= @event.title %></h1>
<p>Description: <%= @event.description %></p>
<p>Creator: <%= link_to @event.creator.username, user_path(@event.creator) %></p>
<div>
<h4>Attendees:</h4>
<% @event.attendees.each do |attendee| %>
    <p><%= attendee %></p>
<% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PrivateEvents</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <% if current_user %>
        <p>Hello <%= link_to current_user.username, user_path(current_user) %><p>
      <% else %>
        <p>You are not logged in</p>
      <% end%>
    </header>
    <%= yield %>
  </body>
</html>

app/views/users/index.html.erb
<h1>List of Users</h1>

<ul>
    <% @users.each do |user| %>
        <li><%= user.username %></li>
    <% end %>
</ul>

app/views/users/new.html.erb
<h1>Register a new User!</h1>
<%= form_with model: @user, local: true do |form| %>
    <div>
        <%= form.label :username, "Name"  %>
        <%= form.text_field :username %>
    </div>
    <br>
    <div>
        <%= form.submit %>
    </div>
<% end %>

app/views/users/show.html.erb
<h1>Profile for <%= @user.username %></h1>

<h4>Created Events</h4>
<% @user.created_events.each do |event |%>
    <div>
        <%= link_to event.title, event_path(event) %>
    </div>
<% end %>

<h4>Events you're attending</h4>
<% @user.attended_events.each do |attended_event| %>
    <p><%= attended_event.title %></p>
<% end %>